### ISSUE TITLE
Not working Properly

### ISSUE THREAD

**Issue by 14397faiq** [rtacr/ringtone_set#1]
Hello Sir when i run the set ringtone function it shows me error snapshot. The plugin is not working properly. Can you please help me that how can i use this function

**Comment by rtacr** [comment]
Hello. Do you have any other information about the error? Looking back at the code, i think it might be a path issue because i made it so messy. Is your audio file in the path lib/assets ?

**Comment by 14397faiq** [comment]
Sir that was a permission granted issue i have added these lines before calling the function
                        final status = await Permission.storage.request();

                        if (status.isGranted) {
                          result = await RingtoneSet.setRingtone("h1.mp3");
                          print('is set');
                        }
now the function is showing sucess snapshot but the ringtones getting none in the mobile ringtones setting 
Can you please help me for this

**Comment by 14397faiq** [comment]
Sir that was a permission granted issue i have added these lines before calling the function
                        final status = await Permission.storage.request();

                        if (status.isGranted) {
                          result = await RingtoneSet.setRingtone("h1.mp3");
                          print('is set');
                        }
now the function is showing sucess snapshot but the ringtones getting none in the mobile ringtones setting 
Can you please help me for this

**Comment by Subhajit1999** [comment]
> 
> 
> Sir that was a permission granted issue i have added these lines before calling the function
> final status = await Permission.storage.request();
> 
> ```
>                     if (status.isGranted) {
>                       result = await RingtoneSet.setRingtone("h1.mp3");
>                       print('is set');
>                     }
> ```
> 
> now the function is showing sucess snapshot but the ringtones getting none in the mobile ringtones setting
> Can you please help me for this

@14397faiq Hey, did you solve this in your app? I am having the same problem too. It's showing success but the ringtone is setting to none.

**Comment by 14397faiq** [comment]
this plugin is just setting ringtones only on android 10 version devices
