### ISSUE TITLE
don't work with audio_players

### ISSUE THREAD

**Issue by khaledarafa** [rtacr/ringtone_set#7]
don't work with audioPlayers

https://pub.dev/packages/audioplayers/install

**Comment by rtacr** [comment]
Hi!

Does it give an conflict error or is it just not doing anything?

**Comment by khaledarafa** [comment]
pub get failed (1; So, because soundeffects depends on both audioplayers ^0.19.0 and ringtone_set ^0.0.2, version solving failed.)
exit code 1
